### ISSUE TITLE
Count the number of guesses

### ISSUE THREAD

**Issue by pengxuemoua** [pengxuemoua/guess_the_number#1]
Once the user has guessed correctly, display the number of guesses it took

Hint: add a counter variable in the main function and increment it when the while loop repeats.

**Comment by pengxuemoua** [comment]
Any updates on this @RageKage?

**Comment by pengxuemoua** [comment]
@RageKage FYI, you'll need to create a pull request on this repository, not on Clara's repository. With the merge of my validation branch it overwrote your code. Since the first time you updated your code, I believe you merged your code without creating a branch and a pull request.

**Comment by pengxuemoua** [comment]
@RageKage please see: 

![Github Pull Request Error](https://github.com/pengxuemoua/guess_the_number/assets/121327389/50c94cee-ba90-46d2-8dd7-644a7404667a)

**Comment by RageKage** [comment]
Issue is fixed.
